from __future__ import annotations

from typing import List

from src.models import JobPosting


class MockJobCollector:
    source = "mock"

    def collect(self) -> List[JobPosting]:
        return [
            JobPosting(
                source=self.source,
                external_id="mock-001",
                title="백엔드 개발자 (신입~1년)",
                company="알파랩스",
                company_category="B2B SaaS",
                location="서울 강남구",
                career_level="신입~1년",
                employment_type="정규직",
                url="https://jobs.example.com/postings/1?utm_source=mock",
                posted_at="2026-06-10",
                responsibilities="Java와 Spring Boot 기반 API 서버 개발, 운영 도구 개선, MySQL 쿼리 튜닝 보조",
                qualifications="컴퓨터공학 기초 또는 그에 준하는 학습 경험, Java 기본 문법 이해, 신입~1년차",
                preferred_qualifications="Spring Boot 개인 프로젝트 경험, REST API 설계 경험",
                tech_stack=["Java", "Spring Boot", "MySQL"],
            ),
            JobPosting(
                source=self.source,
                external_id="mock-001-duplicate",
                title="백엔드 개발자 (신입~1년)",
                company="알파랩스",
                company_category="B2B SaaS",
                location="서울 강남구",
                career_level="신입~1년",
                employment_type="정규직",
                url="https://jobs.example.com/postings/1",
                posted_at="2026-06-10",
                responsibilities="같은 공고의 중복 데이터입니다.",
                qualifications="신입~1년차",
                preferred_qualifications="Spring Boot 경험",
                tech_stack=["Java", "Spring Boot", "MySQL"],
            ),
            JobPosting(
                source=self.source,
                external_id="mock-002",
                title="Junior Backend Engineer",
                company="브라보테크",
                company_category="핀테크",
                location="서울 마포구",
                career_level="Junior / Entry",
                employment_type="정규직",
                url="https://jobs.example.com/postings/2",
                posted_at="2026-06-11",
                responsibilities="Build backend services with Python, FastAPI, PostgreSQL.",
                qualifications="Entry-level candidates welcome. Basic HTTP and database knowledge required.",
                preferred_qualifications="Experience with FastAPI, PostgreSQL, or cloud deployment.",
                tech_stack=["Python", "FastAPI", "PostgreSQL"],
            ),
            JobPosting(
                source=self.source,
                external_id="mock-003",
                title="서버 개발 인턴",
                company="차오름소프트",
                company_category="에듀테크",
                location="경기 성남시",
                career_level="채용연계형 인턴",
                employment_type="인턴",
                url="https://jobs.example.com/postings/3",
                posted_at="2026-06-12",
                responsibilities="Node.js 기반 서버와 API 개발, Redis 캐시 적용, 내부 관리자 기능 개선",
                qualifications="JavaScript 기본 문법 이해, 서버 개발에 관심 있는 신입 또는 인턴 지원자",
                preferred_qualifications="NestJS 또는 Express 프로젝트 경험",
                tech_stack=["Node.js", "NestJS", "Redis"],
            ),
            JobPosting(
                source=self.source,
                external_id="mock-004",
                title="Back-end API Developer 1년 이하",
                company="델타플랫폼",
                company_category="커머스 플랫폼",
                location="원격",
                career_level="경력 1년 이하",
                employment_type="계약직",
                url="https://jobs.example.com/postings/4",
                posted_at="2026-06-13",
                responsibilities="Go 기반 API 서버와 배치 시스템 개발, Docker 기반 개발 환경 관리",
                qualifications="백엔드 개발 경험 1년 이하, SQL 기본 사용 가능",
                preferred_qualifications="Docker 사용 경험, PostgreSQL 스키마 설계 경험",
                tech_stack=["Go", "PostgreSQL", "Docker"],
            ),
            JobPosting(
                source=self.source,
                external_id="mock-005",
                title="프론트엔드 개발자 신입",
                company="에코웹",
                company_category="웹 에이전시",
                location="서울 서초구",
                career_level="신입",
                employment_type="정규직",
                url="https://jobs.example.com/postings/5",
                posted_at="2026-06-13",
                responsibilities="React 기반 웹 UI 개발",
                qualifications="프론트엔드 개발 신입",
                preferred_qualifications="TypeScript 경험",
                tech_stack=["React", "TypeScript"],
            ),
            JobPosting(
                source=self.source,
                external_id="mock-006",
                title="백엔드 개발자 3년 이상",
                company="포커스페이",
                company_category="핀테크",
                location="서울 영등포구",
                career_level="경력 3년 이상",
                employment_type="정규직",
                url="https://jobs.example.com/postings/6",
                posted_at="2026-06-14",
                responsibilities="결제 서버 개발 및 Kafka 기반 이벤트 처리",
                qualifications="백엔드 개발 경력 3년 이상",
                preferred_qualifications="Kotlin, Spring Boot, Kafka 운영 경험",
                tech_stack=["Kotlin", "Spring Boot", "Kafka"],
            ),
            JobPosting(
                source=self.source,
                external_id="mock-007",
                title="데이터 분석가 신입",
                company="그로스인사이트",
                company_category="데이터 컨설팅",
                location="서울 중구",
                career_level="신입",
                employment_type="정규직",
                url="https://jobs.example.com/postings/7",
                posted_at="2026-06-15",
                responsibilities="SQL과 BI 도구로 서비스 지표 분석",
                qualifications="데이터 분석가 신입",
                preferred_qualifications="Tableau 대시보드 제작 경험",
                tech_stack=["SQL", "Tableau"],
            ),
        ]
